/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSheetsAppendRouteImport } from './routes/api/sheets-append'
import { Route as ApiExtractAssetRouteImport } from './routes/api/extract-asset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSheetsAppendRoute = ApiSheetsAppendRouteImport.update({
  id: '/api/sheets-append',
  path: '/api/sheets-append',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractAssetRoute = ApiExtractAssetRouteImport.update({
  id: '/api/extract-asset',
  path: '/api/extract-asset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/extract-asset': typeof ApiExtractAssetRoute
  '/api/sheets-append': typeof ApiSheetsAppendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/extract-asset': typeof ApiExtractAssetRoute
  '/api/sheets-append': typeof ApiSheetsAppendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/extract-asset': typeof ApiExtractAssetRoute
  '/api/sheets-append': typeof ApiSheetsAppendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/extract-asset' | '/api/sheets-append'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/extract-asset' | '/api/sheets-append'
  id: '__root__' | '/' | '/api/extract-asset' | '/api/sheets-append'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExtractAssetRoute: typeof ApiExtractAssetRoute
  ApiSheetsAppendRoute: typeof ApiSheetsAppendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sheets-append': {
      id: '/api/sheets-append'
      path: '/api/sheets-append'
      fullPath: '/api/sheets-append'
      preLoaderRoute: typeof ApiSheetsAppendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-asset': {
      id: '/api/extract-asset'
      path: '/api/extract-asset'
      fullPath: '/api/extract-asset'
      preLoaderRoute: typeof ApiExtractAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExtractAssetRoute: ApiExtractAssetRoute,
  ApiSheetsAppendRoute: ApiSheetsAppendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
